### ISSUE TITLE
Node stopped earning points

### ISSUE THREAD

**Issue by bitdeep** [hyperspaceai/hyperspace-node#23]
Hello, my node was producing points normally, after I used same key to try to deploy another nodes on cloud, it stopped procuding points on my desktop with 4090 gpu.

Anything I can do to reset my settings in the network?

**Comment by bitdeep** [comment]
nvm, I'm good now, doing 600 points/day back.

**Comment by cherishyourself** [comment]
So did I, and I hung for a day, but the uptime showed 1000 + hours, but the points were 0。why？i use cli
